### ISSUE TITLE
[BUG] - Statistics section keeps showing data for relocated planets

### ISSUE THREAD

**Issue by cmartinezledo** [eswak/chrome-ogame-ui-extension#1]
The reason is that you are getting that info from the local storage and not from the Ogame API.

So when you relocate one planet, you can see that the local storage keeps both planets. (Old and new coords)
And as a result of that, you will see the planet duplicated in the Statistics section.

**Comment by eswak** [comment]
Hi Carlos,
Thanks for leaving a comment here to report the issue :-)

I no longer play OGame, so I can't really test and maintain this extension anymore.
Maybe a "refresh planet list" button would do the trick. The planet refresh process is [here](https://github.com/eswak/chrome-ogame-ui-extension/blob/master/OGame%20UI%2B%2B/script.js#L677-L687). I'll see when I have time to fix this bug.

In the mean time, you can clear your localStorage to refresh the planet list, but you will also lose all your nearby idles/neighbors comments.

By the way, I see you're from Argentina : I did the spanish translations using google translate, did you notice weird wordings that I could fix ? The translation key/values can be found [here](https://github.com/eswak/chrome-ogame-ui-extension/blob/master/OGame%20UI%2B%2B/script.js#L114) so if you have the motivation you can even create a pull request ^^

**Comment by cmartinezledo** [comment]
Hi Erwan,
Thanks for your reply! I will check those links, and send a PR if necessary.
About the spanish translations, i did not check them, actually i'm playing in English. But i will check this today.

**Comment by eswak** [comment]
I added a reset button in the statistics tab to get around this problem.
