### ISSUE TITLE
Question about my points

### ISSUE THREAD

**Issue by jvignatti** [eswak/chrome-ogame-ui-extension#103]
`Hello, I would like to know how I can do to get my growth data of economy, military and research.

I could see that in the path the information is saved, but I can not understand it if you could help me I would appreciate it.

best regards

> path d="M50,165L50,159.417C52.485,159.227,54.97,159.053,57.455,158.849C61.1,158.549,64.746,158.153,68.391,157.863C71.481,157.618,74.571,157.489,77.66,157.2C80.684,156.918,83.707,156.387,86.731,155.985C89.803,155.576,92.875,155.153,95.947,154.767C99.01,154.381,102.074,154.014,105.137,153.663C108.255,153.306,111.374,153.072,114.492,152.642C117.563,152.218,120.633,151.386,123.703,150.919C126.758,150.454,129.813,150.134,132.868,149.744C135.87,149.361,138.872,149.026,141.874,148.599C145.019,148.151,148.164,147.542,151.31,147.071C154.397,146.608,157.484,146.332,160.572,145.778C163.577,145.238,166.581,144.252,169.586,143.519C172.683,142.763,175.781,142.176,178.878,141.309C181.99,140.439,185.101,139.339,188.213,138.138C191.284,136.952,194.355,134.806,197.426,134.021C199.685,133.443,201.945,133.294,204.205,132.771C208.001,131.891,211.796,130.229,215.592,128.981C218.75,127.942,221.909,126.758,225.067,125.898C228.093,125.074,231.118,124.658,234.144,123.768C237.217,122.863,240.29,121.131,243.363,120.12C246.468,119.099,249.573,118.647,252.678,117.5C255.131,116.594,257.583,114.727,260.036,113.671C263.734,112.079,267.431,111.094,271.129,109.683C274.193,108.515,277.257,107.424,280.321,105.964C283.37,104.512,286.418,101.51,289.467,100.67C291.988,99.975,294.509,99.908,297.03,99.272C300.643,98.36,304.255,96.691,307.868,94.618C310.97,92.837,314.073,88.582,317.176,86.765C319.697,85.289,322.218,84.407,324.738,83.32C328.362,81.757,331.986,79.969,335.61,78.898C338.682,77.989,341.754,77.665,344.827,76.731C347.773,75.836,350.72,73.715,353.666,72.953C356.865,72.126,360.064,72.155,363.263,71.189C366.253,70.286,369.242,65.766,372.232,63.913C375.385,61.959,378.537,60.107,381.69,59.187C384.742,58.295,387.795,58.292,390.848,57.292C393.937,56.28,397.026,52.662,400.115,49.955C403.171,47.277,406.227,43.714,409.283,40.965C412.369,38.189,415.455,36.04,418.541,33.275C421.594,30.539,424.647,27.33,427.701,24.368C430.79,21.372,433.879,19.469,436.967,15.403C437.05,15.294,437.133,15.134,437.216,15L437.216,165Z" class="ct-area"></path

**Comment by eswak** [comment]
hi,

you could run this in your console (in ogame tab): 
```js
copy(config.history[$('[name="ogame-player-id"]').attr('content')])
```
it should copy something like this in your clipboard : 
```
{
  "2017-12-17": {
    "t": 1513546508991,
    "e": 5661362,
    "ep": 31,
    "m": 2171522,
    "mp": 36,
    "h": 5930,
    "hp": 462,
    "r": 422098,
    "rp": 194,
    "g": 6124440,
    "gp": 61,
    "s": 13507,
    "p": 10
  },
  "2017-12-18": {
    "t": 1513608369250,
    "e": 5688014,
    "ep": 31,
    "m": 2298174,
    "mp": 33,
    "h": 5930,
    "hp": 464,
    "r": 422098,
    "rp": 195,
    "g": 6251092,
    "gp": 59,
    "s": 13517,
    "p": 10
  }
}
```
t: time
e: economy (points)
ep: economy position
m: military
h: honor
r: research
g: general
s: ships
p: planets
