### ISSUE TITLE
Nearby Players (BUG) - Waiting XXXX seconds for a free mission slot

### ISSUE THREAD

**Issue by d4n13lus** [eswak/chrome-ogame-ui-extension#105]
Hi, i have a problem when i want to spy players from the extension table (where you see a list of all inactives/etc). Sometimes works fine and i can send a number of spy missions equal to my free slots, but sometimes (now) it display a message as the one i write in the title: "Waiting XXXX seconds for a free mission slot", but i have all the slots free!

I try to unnistall the extension, but the error persist :(

any idea, thanks

**Comment by d4n13lus** [comment]
https://postimg.org/image/4vo9x4leb/

**Comment by d4n13lus** [comment]
https://github.com/eswak/chrome-ogame-ui-extension/issues/92

maybe this issue can solve my problem, i will check it

**Comment by d4n13lus** [comment]
solved

**Comment by eswak** [comment]
Hi,

how did you solve it ??

**Comment by d4n13lus** [comment]
finally, as the info in #92, the error was produced by a noob player i cant spy ;)

**Comment by sigod** [comment]
So, how was this solved? Does the extension detect noob players and doesn't attempt to scan them?

**Comment by d4n13lus** [comment]
@sigod, simple, when this message appears, check this player and if its a noob, mark the line in the list for future reference.

**Comment by pawelzwronek** [comment]
I think i've fixed this in #107

**Comment by pawelzwronek** [comment]
@eswak can you find some time to merge it? 🙏 Think players's eagerly waiting for this.

**Comment by eswak** [comment]
sorry :(

it's merged; I'll publish now
