### ISSUE TITLE
REQUEST (NEARBY PLAYERS) - Less "travel time" filtering 

### ISSUE THREAD

**Issue by d4n13lus** [eswak/chrome-ogame-ui-extension#108]
I would like to  filter the list of nearby players for less time than one hour, **30 minutes** for example. I am playing in a fast universe in which the espionage probes have load capacity and can be used to attack inactives, and filtering the time for only an hour makes some targets far away.

https://s13.postimg.org/9mu7pxmt3/000427.png

Thanks ESWAK

**Comment by eswak** [comment]
I added a "<30m" button in the next version
