### ISSUE TITLE
Spy queue not working anymore

### ISSUE THREAD

**Issue by injNinja** [eswak/chrome-ogame-ui-extension#109]
nvm

**Comment by injNinja** [comment]
are there any particular settings to make it work? i always get the no slots error!

**Comment by pawelzwronek** [comment]
Can you give some more info when particularly it's not working please.
I've noticed that opening new browser tab with ogame, while spy queue is working is an issue but fixed it in last PR #111

**Comment by injNinja** [comment]
no particular situation, randomly it stops working.

no tabs opened, nothing, one second before it works then it starts coloring all the tiles in red with no recovery 
Inviato da iPhone

**Comment by eswak** [comment]
I guess it's closed because you edited the original post
