### ISSUE TITLE
All espionage going to Error2

### ISSUE THREAD

**Issue by kubealex** [eswak/chrome-ogame-ui-extension#117]
With new version, errors are never recovered.

**Comment by pawelzwronek** [comment]
AAAAAA 😕  😱  😄 
Does this behavior differ somehow from previous version? Can you describe situation with errors?

**Comment by sigod** [comment]
It doesn't recover from "no fleet slots available". After two attempts it says "Error 2" and tries next target.

**Comment by injNinja** [comment]
Yep!

Il dom 16 set 2018, 02:35 sigod <notifications@github.com> ha scritto:

**Comment by sigod** [comment]
Actually, it was a one-time issue. Now it works as it should be. I guess it can break under certain conditions.
