### ISSUE TITLE
Use Page-Language instead of Browser Language

### ISSUE THREAD

**Issue by ControlTheBit** [eswak/chrome-ogame-ui-extension#13]
It would be great if one could use the Game language instead of the Browser language.
My situation is that I have my OS and Browser set to English, but I'm playing in a German universe.  Therefore the UI is German and it would be great if the extension would now also be German.

I can provide a Pull Request for this, if needed. 

Thank you!

**Comment by eswak** [comment]
I'll include this in today's release (as well as your german translations).
thanks !
