### ISSUE TITLE
Wrong calculations with servers that use comma as their decimal separator

### ISSUE THREAD

**Issue by cmartinezledo** [eswak/chrome-ogame-ui-extension#14]
Recently moved to ogame.ar to take care of a friend account. And for my surprise buildings took years to finish :rofl: And when I moved the mouse to the building cost resources I saw the comma, so instead of picking up 3.00 it´s taking 300,00. 
So all calculations are a disaster when playing on that universes.

**Comment by eswak** [comment]
Should be fixed in the next release
