### ISSUE TITLE
Resources : overlapping text when string is too long

### ISSUE THREAD

**Issue by eswak** [eswak/chrome-ogame-ui-extension#16]
_Bug report from the google store :_ 

When ressource text is too long, the violet text is overlapping with standard game info.

![](https://image.prntscr.com/image/2f4b3a35c6e145d3a17a02e69c273329.png)

**Comment by shonderdos** [comment]
There ain't a lot of space to play with.
I could force the text to stay on one line and hide all exceeding text.
Otherwise I might remove the total time from up there and display it in the pop-up when you hover over the icon.

**Comment by eswak** [comment]
this is somewhat hacky but you could add text to the resource tooltip with this code : 
```js
var tooltips = JSON.parse(
  window.initAjaxResourcebox.toString()
    .replace('function initAjaxResourcebox(){reloadResources(', '')
    .replace(new RegExp('\\);}$'), '')
);
var newMetalTooltip = tooltips.metal.tooltip.replace(
  '</table>',
  [
    '<tr class="enhancement"><th>Storage left :</th><td>15h 35m</td></tr>',
    '<tr class="enhancement"><th>Total storage time :</th><td>1d 4h</td></tr>',
    '</table>'
  ].join('')
);
changeTooltip($("#metal_box"), newMetalTooltip);
```

**Comment by eswak** [comment]
we could keep the remaining storage time under the resources, and add the total storage time in the tooltip, since it's a less important information

what's your opinion on this @shonderdos ?

I can make the PR ^^

**Comment by shonderdos** [comment]
I think the tooltip should contain both the `Time Untill Full` and `Total Storage Time`. And delete the `Total Storage Time` from the original place.

I'm working on a PR myself aswell =)
