### ISSUE TITLE
Add note text field when viewing spy reports

### ISSUE THREAD

**Issue by eswak** [eswak/chrome-ogame-ui-extension#40]
It would be more practical to note directly from the messages tab informations about the planets we just spied

**Comment by pawelzwronek** [comment]
I can handle it if you want?

**Comment by eswak** [comment]
oh yeah sure why not ^^

**Comment by eswak** [comment]
in the `nearby players` extension it would make more sense atm because the note fields are only displayed in these 2 tabs

i'm thinking about a "favorite planets" system, that could work with gameforge rules because universeview has such a system ^^ then there will be note fields in the uipp extension but until then only nearby players has them
