### ISSUE TITLE
Console error : Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by eswak** [eswak/chrome-ogame-ui-extension#45]
Issue reported from the google chrome store

> On a Linux mashine i'm clicked on a "Statistics" button and got error on Chromium console: (unknown) Uncaught TypeError: Cannot read property 'join' of undefined at <anonymous>:96:48 at Array.map (native) at HTMLLIElement.<anonymous> (<anonymous>:94:47) at HTMLLIElement.dispatch (https://gf3.geo.gfsrv.net/cdn8c/095a3a537441223e34647ad44e30ec.js:2:44760) at HTMLLIElement.r.handle (https://gf3.geo.gfsrv.net/cdn8c/095a3a537441223e34647ad44e30ec.js:2:41480)

**Comment by eswak** [comment]
I don't think the error comes from this script.

**Comment by andreili** [comment]
This error is repeated only in browsers under Linux.
![image](https://user-images.githubusercontent.com/1331777/27815820-f2de36ec-608f-11e7-98da-9243b8652812.png)

**Comment by andreili** [comment]
I found the problem areas - the list of incorrect variable config.my.planets:
![image](https://user-images.githubusercontent.com/1331777/27816382-e1641dec-6093-11e7-9290-52217a3682c0.png)

**Comment by andreili** [comment]
The reason is that the script does not delete deleted data from its data, which leads to this error.
Maybe it's worth adding a reset of the statistics of the planets when updating the list of players?

**Comment by eswak** [comment]
`config.my.planets` stores the current player's planets, with mine levels, current production, etc.
it is not refreshed when we update the list of players (which happens hourly, and we don't want to visit all our planets every hour to collect the mine levels etc)

The property `coords` seems to be missing though, which is weird. Did you delete one of your planets ?
Thanks for the insight, I'll look deeper into this bug.

**Comment by andreili** [comment]
Yes, when I founded a new colony, I deleted it until I got a variant with the optimal number of fields.

**Comment by eswak** [comment]
the new version should fix it, can you tell me if it's ok ? should be published in about an hour
