### ISSUE TITLE
#14 is still a [Bug]

### ISSUE THREAD

**Issue by cmartinezledo** [eswak/chrome-ogame-ui-extension#54]
Tried today, and same result #14. A 4h 3xm waiting, turns into 3d 4h 👎 
Actual cost: 8.522M Metal
Actual Metal in planet: 8.015.046 
Difference: 507.223

`<div class="t_ContentContainer t_clearfix t_Content_cloud" style="width: auto; height: auto;">8.522.269 Metal</div>`
Actual production: 111.405 metal per hour

![untitled](https://user-images.githubusercontent.com/10406699/28234865-fb9b63c4-68da-11e7-8987-8c5e93fabb08.png)

**Comment by eswak** [comment]
it's a conversion of the resource cost in time (it takes you 3d4h to gather 8.522M metal on this planet)

adding remaining time would be redundant (you already have the "buildable in..." information above)

**Comment by eswak** [comment]
I don't see any issue, what do you think would make the information more clear ?

**Comment by cmartinezledo** [comment]
@eswak It does not take 3d, it actually takes 4hours. That's the bug. It happens when the building requires more than 1 million

**Comment by eswak** [comment]
if it costs `8.522.269` metal and your production is `111.405`/h the cost is `8522 / 111 = 76h = 3d4h`.

it's not the REMAINING time before being able to build, it's just a conversion of the cost in time based on your planet's production

**Comment by cmartinezledo** [comment]
@eswak And why don't we show the remaining time based on the planet resources? Would not that be a little more useful?

**Comment by eswak** [comment]
idk because the remaining time is already displayed (you circled it ("construccion possible a partir de")) so it would be kind of redundant

**Comment by cmartinezledo** [comment]
That´s if you have commanders.

**Comment by pawelzwronek** [comment]
I think that to improve readability the remaining time could be moved below cost text. When cost text is white(user have enough res) displayed time stay like today, but when cost text is red(not sufficient res) displayed time become negative number with time remaining to gather this particular resource. BUILDABLE_IN and BUILDABLE_NOW strings would be removed.

**Comment by pawelzwronek** [comment]
Like this #65 
Positive value of time changed to italic to lower it's importance not to mislead user that this is counting down or sth. I think it's low priority information.

**Comment by eswak** [comment]
![remainingtime](https://user-images.githubusercontent.com/6916865/28797710-8238ec5c-7642-11e7-9050-144b0dab4142.png)
would it make more sense to you guys if we just keep the remaining time under resources we don't have enough of ?

**Comment by pawelzwronek** [comment]
For me it's ok :)  #65 is doing this now so you only have to remove italic text
