### ISSUE TITLE
Favorites tab

### ISSUE THREAD

**Issue by ggcatu** [eswak/chrome-ogame-ui-extension#6]
I would pull the favorites tab, but there's still an issue.
Player data gets pulled from a Weekly updated info, so when you add some "New" planets, you can't see them on the favorite tab, since I made a way to add them by coords,

![image](https://cloud.githubusercontent.com/assets/9058818/19838614/a79d175a-9ea9-11e6-9d61-33015f12a510.png)

Need to add a way to update it faster.
Was thinking about adding another box to "Update player" witch would get all their planets from the DAILY updated info, so the planet would appear.

Is not really an Issue, just didn't know where to discuss about it, my first time contributing to a project.

**Comment by eswak** [comment]
It's a good place to discuss this :-) 

So, what you're saying is : you can add a player as "favorite" and see your "favorite players" in a tab, but these player's planets are only updated weekly ?

Is it a limitation induced by the routes I'm calling (`/api/universe.xml` and `/api/highscore.xml`) ?
Or can the problem be solved by calling `loadUniverseApi()` ?

**Comment by ggcatu** [comment]
Limitation due to (`/api/universe.xml` and` /api/highscore.xml`)

**Comment by eswak** [comment]
hi @ggcatu did you find a work around this ?

**Comment by ggcatu** [comment]
Seems like you are playing again oGame! 
Me too, might take a look later :+1:
