### ISSUE TITLE
A feedback text field

### ISSUE THREAD

**Issue by pawelzwronek** [eswak/chrome-ogame-ui-extension#61]
To ease for users giving feedback a text filed in UI++ settings tab with simple 'Send' button would be great. It would be faster and more anonymous than google store comments.

**Comment by pawelzwronek** [comment]
To ease even more and to encourage users this button could be placed on the bottom of every tab like this:
![feedback](https://user-images.githubusercontent.com/23583498/28580753-c04477a0-7160-11e7-8315-9977cc4fad59.png)

**Comment by eswak** [comment]
👍

**Comment by pawelzwronek** [comment]
Is it possible to use google analytics to receive any string(with feedback text)? Or maybe github has any API to gather and display a list of strings?

**Comment by eswak** [comment]
hmmm I didn't think about github but they have a really good API

I could make a text field that post new issues ? then I could use labels to sort things out (bugs vs ideas etc)

**Comment by pawelzwronek** [comment]
We can try github then. Is it possible to add custom labels? I see also 2 or 3 radio buttons: 'Idea', 'Bug', 'Greetings' (optional:). I'm afraid of spam only.
But first I think we should make Settings tab more userfriendly. Now it's a little cluttered.

**Comment by pawelzwronek** [comment]
Take a look at 66a52c1fa8eda5ea9d598c6608d744788722cf31
and the data goes here https://docs.google.com/spreadsheets/d/1OaPNzC-n4VIZ62bYb24TGU_9-Ky-ViCLoGP-aU81uCE/edit?usp=sharing

**Comment by eswak** [comment]
nice ^^ can you submit a PR so I can test it ?

**Comment by pawelzwronek** [comment]
Without PR it's unable to test it? 🤔

2017-09-25 16:39 GMT+02:00 Erwan Beauvois <notifications@github.com>:

**Comment by eswak** [comment]
It's just that I'm a noob and I don't know how to test otherwise 😝 

I moved the feedback before the donation section so people would notice it better

**Comment by pawelzwronek** [comment]
:point_right:` git checkout 66a52c1fa8eda5ea9d598c6608d744788722cf31` :point_left: :grinning:

**Comment by eswak** [comment]
I tried `cherry-pick` but the commit couldn't be found 😢
