### ISSUE TITLE
Galaxy View & Spy Section

### ISSUE THREAD

**Issue by cmartinezledo** [eswak/chrome-ogame-ui-extension#71]
Hi,

I think that nowadays, the best galaxy view extension is [UniverseView](https://chrome.google.com/webstore/detail/universeview-extension/ipmfkhoihjbbohnfecpmhekhippaplnh?hl=en) even better than AGO. Provides a clean and tidy UI and also enhance it with OTrashSim. 

Wouldn't be better to rely on this extension for the Galaxy View?
And for the spy section, I think that Skynet 'Raidar' > AGO also. But as Skynet extension seems to be  abandoned, we could go for UI++ version 😃 

Hope my suggestion makes sense for UI++ backlog

**Comment by eswak** [comment]
Thanks for the extension names, I'll definetely check these out ^^

**Comment by eswak** [comment]
I like them both, you're right they're cool ^^

They're not conflicting with OGame UI++ either so I guess we're fine ?

**Comment by cmartinezledo** [comment]
Yeah! I have been playing with UniverseView, Skynet and OGame UI++
Have not seen any conflict in the last 6~7 months
