### ISSUE TITLE
Include level matrix not for supplies, but also shipyard, etc

### ISSUE THREAD

**Issue by mas-designs** [eswak/chrome-ogame-ui-extension#84]
Via the statistics tab, you can see all the planets + the corresponding levels for metal, crystal and deut, how about including this also for shipyard, research, etc

**Comment by eswak** [comment]
Hi, thanks for coming here :-)

I'd like to, but it's already borderline to include the mine's levels on a single page.
The OGame staff won't approve this extension if it simulates premium features, and if we start to include other building's levels it will look a lot like the imperium view (which is a commander feature).

You could fork the repository and code this, but I'm not too keen on publishing this kind of features for OGame UI++ myself.

**Comment by mas-designs** [comment]
okay, yeah I agree :-)
