### ISSUE TITLE
Make settings tab more userfriendly

### ISSUE THREAD

**Issue by shonderdos** [eswak/chrome-ogame-ui-extension#85]
As @pawelzwronek mentioned, we should make the settings tab more userfriendly. The thing that bothers me most is the visualisation of the features. The red lines confused me as if the feature was on and the others were off.

Here Are some changes I would like to make, feel free to add or comment:

- [ ] Change visualisation of features 
- [ ] Add small description for each feature
- [ ]  Add section titles
- [ ] Change tab name to settings
- [ ] Change reset buttons to checkboxes

**Comment by pawelzwronek** [comment]
Agree 👍 ^^ but current name of tab it's ok for me. 
Suggestion for the reset buttons: 4 checkboxes: `Points history`, `Planet notes`, `Your planets`, `Universe` plus one `Reset` button which reset selected data. Each checkbox has description or in tooltip or as a simple label always visible.

**Comment by pawelzwronek** [comment]
As for the features configuration:
- remove the red outlines but leave those small ones
- below the picture insert short name of a feature
- on hover over the picture or on click on the short text the description would appear

**Comment by eswak** [comment]
Alright why not, if you 2 don't like it; I guess other people don't like it ^^

If you can't manage to fit all on one screen you could use accordions like in the alliance page where you can click on the title and hide/show the whole section.

I used images at first to show the features because I didn't want to translate the features in several languages & I think english is not really clear for everyone.
Maybe images without the confusing red outlines could work ?

**Comment by pawelzwronek** [comment]
Another idea: move as much as possible switches to where the features are e.g.: on the statistic page in one of the corner there is a gear icon when pressed an outline on every feature would appear. When a feature is pressed you switch it enable/disable just like in settings page now . When a gear icon is pressed again all dimmed features and outlines hides. It could be difficult to code though.

**Comment by shonderdos** [comment]
But then the switches are all over the game/website/application. I prefer the switches on one page like this:
![screen shot 2017-08-31 at 09 15 09](https://user-images.githubusercontent.com/5478388/29911100-ebb282c2-8e2c-11e7-9fc9-755845ef4f45.png)

I like the checkbox idea to reset. I think we should go with a tooltip

**Comment by eswak** [comment]
I like where this is going ^^

we can keep the text in english (at least it's better than no text at all), and if people want to help to add translations there will be a separate process for that ^^

**Comment by pawelzwronek** [comment]
The idea of gears have 
Pros:
- you have the context of a setting at glance
- you see effect of a setting immediately
- setting page is smaller
- chrome's DevToll e.g. use this mechanism and it works :)
- compact solution

Cons:
- lack of description of a feature  (we can add one)
- ? settings in different places
- more coding (I can handle this part)

I like your image with tiles but lets's leave it only for features that's hard to setup with a 'gears' idea.

**Comment by pawelzwronek** [comment]
Try this one 9263c990cb62b9f3e4a898c0f4a0bfdf1f87e3b9
![gear](https://user-images.githubusercontent.com/23583498/30192734-84431a2a-9449-11e7-8473-83ce9dfc74b2.png)

**Comment by pawelzwronek** [comment]
How do you like it @shonderdos ? I have also in mind to show just once a tooltip pointing to a gear icon so the user won't miss it :)

**Comment by pawelzwronek** [comment]
And this #95 
![reset section](https://user-images.githubusercontent.com/23583498/30243596-595348ca-95ad-11e7-86e1-ffd31bc51ca3.png)

**Comment by shonderdos** [comment]
I don't have time this week to work on the project, maby I have some spare time this weekend. Can't checkout 9263c99 atm but maby @eswak can take a look. I like the solution in #95 !

**Comment by eswak** [comment]
I'm on holiday, won't have a computer until mid-next-week. Sorry 😊

**Comment by eswak** [comment]
oh by the way this has been merged last week !
@shonderdos make sure to include the latest changse when you're working on the settings page ;-)

**Comment by pawelzwronek** [comment]
Seems shonderdos is on a very long vacations 😉 How do you like the gear @eswak ? Should I polish it and make PR?

**Comment by eswak** [comment]
why not ^^
