### ISSUE TITLE
Donate button is in french

### ISSUE THREAD

**Issue by pawelzwronek** [eswak/chrome-ogame-ui-extension#87]
Like this. I dont understand it so I would not click it :P
 ![donate](https://user-images.githubusercontent.com/23583498/29895525-ab70fac0-8dd9-11e7-8be8-c8656465fadc.png)

**Comment by eswak** [comment]
I'm not sure I can "internationalize" this (it's a code snippet provided by paypal) but maybe I can generate it in english ^^

maaaaaybe that's why nobody clicks it 😄 

~or maybe people would rather buy dark matter if they were to put money into the game~

**Comment by pawelzwronek** [comment]
:rofl:

**Comment by pawelzwronek** [comment]
Or put it with different languages and show only right one?

**Comment by eswak** [comment]
sounds complicated :p
