### ISSUE TITLE
List nearby moons with the player's military score

### ISSUE THREAD

**Issue by eswak** [eswak/chrome-ogame-ui-extension#91]
So you can easily know if there are some threatening moons nearby your planets.
Not sure how to present it nor where it should be displayed.

Probably should go in the "nearby players" extension.

**Comment by cmartinezledo** [comment]
I think you can close this one @eswak 
As "nearby players" feature was not approved by GF.

**Comment by eswak** [comment]
yeah :-/ I definetely won't implement this you're right
