### ISSUE TITLE
Spying from nearby players tab

### ISSUE THREAD

**Issue by injNinja** [eswak/chrome-ogame-ui-extension#92]
Hello, 

I want to report that spying players from the nearby tab is not possible anymore from today, it always tells that you have to wait x seconds for a free slot, where x is the first returning mission, even if you have all free slots.

Thank you

**Comment by eswak** [comment]
hi, do you have the proper count of spy probes on your planet ?

I also noticed that when the player is a begginer or an admin or anything we can't spy, it acts just like you describes, and acts like you have no free slots left

@pawelzwronek can you look into this ?

**Comment by injNinja** [comment]
Im in top 40, ofc I have enough probes on all planets!

Inviato da iPhone

**Comment by pawelzwronek** [comment]
It seems now you can only send satellites when in a galaxy view. Solution for that might be first automatic entering a galaxy view when 'Nearby idles' is clicked and then instant showing an actual list of idlers.
